#spring:
#  application:
#    name: ${SPRING_APPLICATION_NAME:frontend}

#zuul:
#  prefix: ${ZUUL_PREFIX:/services}
#  routes:
#    tasks-service:
#      url: ${TASKS-SERVICE_URL:http://localhost:8080}

server:
  port: ${SERVER_PORT:8080}
