spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: ${SPRING_APPLICATION_NAME:users-service}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:123}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:users_db}
server:
  port: ${SERVER_PORT:8082}