spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ${SPRING_APPLICATION_NAME:users-service}

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_LOGIN:users_user}
    password: ${DB_PASSWORD:12345}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:users_db}
server:
  port: ${SERVER_PORT:8082}