spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: ${SPRING_APPLICATION_NAME:register-service}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:students}
server:
  port: ${SERVER_PORT:8080}
url:
  host: http://localhost
  port:
    user: 8080
    auth: 8080
    jsf-frontend: 8080
    register: 8080
  path:
    user: /api/users
    auth: /api/credentials
    register: /api/register
